### ISSUE TITLE
这个具体怎么用呀

### ISSUE THREAD

**Issue by hxqup** [yifan-hou/force_control#2]
你好，我现在在学习用ur机械臂做力控打磨，我看了看readme，没太看明白，想请问一下这个可以在仿真环境下测试吗，还是说是要连接实体机械臂的

**Comment by yifan-hou** [comment]
你好！不好意思之前没有在维护这个包。我刚刚更新了readme 有具体的例子。这个包只包含力控算法，仿真或者实物都可以用。

This package is algorithm only. At every step, you need to provide robot status, reference position and force, then the algorithm computes a target pose that you can send to your robot.
