### ISSUE TITLE
Set force control axes and dimension问题

### ISSUE THREAD

**Issue by qingqaq77** [yifan-hou/force_control#4]
你好，readme文件里这个部分int n_af = 6;不太理解 是不是应该设为3？
// HFVC, compliant translational motion, rigid rotation motion 
RUT::Matrix6d Tr = RUT::Matrix6d::Identity();
int n_af = 6;
controller.setForceControlledAxis(Tr, n_af);

**Comment by yifan-hou** [comment]
You are right, that is a typo. It should be `int n_af = 3` here.

**Comment by yifan-hou** [comment]
Fixed.
